### ISSUE TITLE
Add siimple-table--fixed modifier to table component

### ISSUE THREAD

**Issue by jmjuanes** [siimple/siimple#52]
Add `siimple-table--fixed` modifier to table component to automatically divide equally the width of the columns across the table, regardless of content inside the cells.

```css
.siimple-table--fixed {
    table-layout: fixed;
}
```
Reference: https://www.w3schools.com/csSref/pr_tab_table-layout.asp

Tasks: 
- [x] Add `siimple-table--fixed` class to `scss/components/_table.scss`.
- [x] Add to documentation.
